-- 1. Создаем таблицу для товаров
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  price numeric NOT NULL,
  image text,
  category text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Разрешаем всем читать товары (без этого сайт не сможет показать меню)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read products" ON public.products FOR SELECT USING (true);

-- 3. Добавляем пару стартовых товаров для примера
INSERT INTO public.products (name, description, price, image, category)
VALUES 
('Круассан классический', 'Воздушный французский круассан со сливочным маслом', 15000, 'https://images.unsplash.com/photo-1555507036-ab1f4022115c?w=500', 'home'),
('Хлеб на закваске', 'Хрустящий ремесленный хлеб', 20000, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500', 'retail');
